trigger:
  - main

pr:
  - main

strategy:
  matrix:
    linux:
      vmImage: ubuntu-latest
    windows:
      vmImage: windows-latest

pool:
  vmImage: $(vmImage)

steps:
  - task: Cache@2  # Not required, but Qodana will open projects with cache faster.
    inputs:
      key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
      path: '$(Agent.TempDirectory)/qodana/cache'
      restoreKeys: |
        "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
        "$(Build.Repository.Name)"
  - task: QodanaScan@2024
    inputs:
      args: --ide,QDNET
    env:
      QODANA_TOKEN: $(QODANA_TOKEN_TESTS)
      AGENT_USE_NODE10: true
