name: QodanaScanJob
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev
      - 'releases/*'

jobs:
  qodana-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@latest
        with:
          args: --ide,QDNET
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_TESTS }}

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{ runner.temp }}/qodana/results/
